<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_OneClick $this
 */
?>
<?php
if ($this->isSupportedProduct() && $this->isButtonEnabled()) :
    ?>
    <?php echo $this->addCssStylesBlock(); ?>

    <div id="oyst-1click-button-wrapper">
        <!--<?php echo $this->escapeHtml($this->getButtonCustomization('product_page_')); ?> -->
        <div id="oyst-1click-button" <?php echo $this->escapeHtml($this->getButtonCustomization('product_page_')); ?>></div>
    </div>
    <script>
        <?php echo $this->oneClickButtonPickToFirstAddToCartButtons(); ?>

        (function () {
            if ("function" === typeof oystOneClick) {
                var oystOneClickConfig = {
                    'oneClickUrl': <?php echo $this->getOneClickUrl(); ?>,
                    'addToCartProductFormId': 'product_addtocart_form',
                    'isProductAddtocartFormValidate': <?php echo $this->escapeHtml($this->isProductAddtocartFormValidate()); ?>,
                    'addtocartButtonsClass': <?php echo Zend_Json::encode(
                        Mage::getStoreConfig('oyst/oneclick/product_page_buttons_wrapper_class')
                    ); ?>
                };
            
                oystOneClick(oystOneClickConfig);
            } else {
                console.error("Missing function oystOneClick");
            }
        })();
    </script>
<?php endif;
echo Mage::helper('oyst_oneclick')->getOneClickJs();
