sudo: false
language: php

php:
#  - 5.3
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0

matrix:
  fast_finish: true
  #allow_failures:
  #  - php: 5.6
  exclude:
    # Newer Magento versions uses newer PHP versions
    - php: 5.3
      env: MAGENTO_VERSION="magento-mirror-1.9.3.2"
    # Old Magento Versions are not officially supported to run with PHP 5.5
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    # Old Magento Versions are not officially supported to run with PHP 5.6
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.0.1"
    # Old Magento Versions are not officially supported to run with PHP 7.0
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.0.1"

env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/oyst-magento/app/code/community/Oyst/Oyst/Test
  matrix:
    - MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - MAGENTO_VERSION="magento-mirror-1.9.3.1"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/bin

install:
  - composer install --no-interaction
  - phpenv rehash

script:
  - mkdir -p build/logs
  - curl --retry 2 --retry-delay 5 -f -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
  ## PHP CodeSniffer disable error on exit
  - ./bin/phpcs --config-set ignore_warnings_on_exit 1
  ## PHP CodeSniffer with ECG Magento Code Sniffer Coding Standard
  #- rm -Rf vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Ecg &&
  #  cp -R vendor/magento-ecg/coding-standard/Ecg vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/ &&
  #  ./bin/phpcs --standard=Ecg --extensions=php,phtml --ignore=bin,lib,vendor $TRAVIS_BUILD_DIR
  ## PHP Copy/Paste Detector
  - ./bin/phpcpd --exclude bin --exclude lib --exclude vendor $TRAVIS_BUILD_DIR
  ## PHP Mess Detector
  - ./bin/phpmd $TRAVIS_BUILD_DIR text cleancode --exclude bin,lib,vendor --ignore-violations-on-exit
  - ./bin/phpmd $TRAVIS_BUILD_DIR text codesize --exclude bin,lib,vendor --ignore-violations-on-exit
  - ./bin/phpmd $TRAVIS_BUILD_DIR text controversial --exclude bin,lib,vendor --ignore-violations-on-exit
  - ./bin/phpmd $TRAVIS_BUILD_DIR text design --exclude bin,lib,vendor --ignore-violations-on-exit
  - ./bin/phpmd $TRAVIS_BUILD_DIR text naming --exclude bin,lib,vendor --ignore-violations-on-exit
  - ./bin/phpmd $TRAVIS_BUILD_DIR text unusedcode --exclude bin,lib,vendor --ignore-violations-on-exit
  ## PHPLOC
  - ./bin/phploc $TRAVIS_BUILD_DIR --exclude bin --exclude lib --exclude vendor
  ## LINT
  - find $TRAVIS_BUILD_DIR/app -type f -name \*.php -exec php -l {} \;
  ## Magento EQP Coding Standard
  - if [[ "${TRAVIS_PHP_VERSION:0:3}" = "5.6" ]]; then
      composer config http-basic.repo.magento.com $MAGENTO_REPO_PUBLIC_KEY $MAGENTO_REPO_PRIVATE_KEY &&
      composer require -n magento/marketplace-eqp &&
      rm -Rf vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/MEQP1 &&
      cp -a vendor/magento/marketplace-eqp/MEQP1 vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/MEQP1 &&
      cp -a vendor/magento/marketplace-eqp/Utils vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Utils &&
      ./bin/phpcs --standard=MEQP1 --extensions=php,phtml --ignore=bin,lib,vendor --severity=10 $TRAVIS_BUILD_DIR;
    fi
  ## PHPCompatibility
  - rm -Rf vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility &&
    cp -a vendor/wimg/php-compatibility vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility &&
    ./bin/phpcs --standard=PHPCompatibility --extensions=php,phtml --ignore=bin,lib,vendor --runtime-set testVersion ${TRAVIS_PHP_VERSION:0:3} $TRAVIS_BUILD_DIR

notifications:
  email:
    on_success: never  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
