<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 *
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_Adminhtml_Field_LogActions $this
 */

$oystHelper = Mage::helper('oyst_oneclick');
?>
<style>
</style>

<div>
    <table>
        <thead>
            <tr class="oyst-log-actions-header">
                <th><?php echo $oystHelper->__('Log file'); ?></th>
                <th>
                    <?php echo $oystHelper->__('Log rows'); ?>
                    <div class="field-tooltip"><div><?php echo $oystHelper->__('from EOF'); ?></div></div>
                </th>
                <th><?php echo $oystHelper->__('Actions'); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <select id="oyst-log-file-name">
                        <?php foreach ($this->getLogFiles() as $file): ?>
                            <option value="<?php echo $file; ?>"><?php echo $file; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="file-rows">
                    <input type="number" id="oyst-log-file-rows" name="lines" min="1" max="1000" value="100">
                </td>
                <td>
                    <div class="oyst-actions">
                        <button type="button" onclick="getUrl('<?php echo $this->getButtonUrl('download'); ?>')">
                            <?php echo $oystHelper->__('Download'); ?>
                        </button>
                        <button type="button" onclick="getUrl('<?php echo $this->getButtonUrl('delete'); ?>')">
                            <?php echo $oystHelper->__('Delete'); ?>
                        </button>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
