<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @see Oyst_OneClick_Block_Adminhtml_Notifications Notifications
 */

/** @var Oyst_OneClick_Helper_Data $oystHelper */
$oystHelper = Mage::helper('oyst_oneclick');

/** @var Oyst_OneClick_Block_Adminhtml_Notifications $this */
if (!$this->isInitialized()): ?>
    <div class="notification-global">
        <span class="f-right">
            <a href="<?php echo $this->getSkipUrl() ?>">
                <?php echo $oystHelper->__('Remove this message') ?></a>
        </span>
        <strong><?php echo $oystHelper->__('1-Click has been installed.') ?></strong>
        <?php
        echo $this->helper('oyst_oneclick')->__(
                'Click <a href="%s">here</a> to set up your settings.',
                $this->getManageUrl()
        ) ?>
    </div>
<?php endif;
