<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @see Oyst_OneClick_Block_Adminhtml_Notifications Notifications
 */

/** @var $this Oyst_OneClick_Block_Adminhtml_Notifications */

/** @var Oyst_OneClick_Helper_Data $oystHelper */
$oystHelper = Mage::helper('oyst_oneclick');
?>

<!-- Notification for OneClick -->
<?php if (!$this->isInitialized('oneclick')): ?>
    <div class="notification-global">
        <span class="f-right">
            <a href="<?php echo $this->getSkipUrl('oneclick') ?>">
                <?php echo $oystHelper->__('Remove this message') ?></a>
        </span>
        <strong><?php echo $oystHelper->__('1-Click has been installed.') ?></strong>
        <?php
        echo $oystHelper->__(
                'Click <a href="%s">here</a> to set up your settings.',
                $this->getManageUrl('oyst_oneclick')
        ) ?>
    </div>
<?php endif; ?>

<!-- Notification for Freepay -->
<?php if (!$this->isInitialized('freepay')): ?>
    <div class="notification-global">
        <span class="f-right">
            <a href="<?php echo $this->getSkipUrl('freepay') ?>">
                <?php echo $oystHelper->__('Remove this message') ?></a>
        </span>
        <strong><?php echo $oystHelper->__('FreePay has been installed.') ?></strong>
        <?php echo $oystHelper->__(
            'Click <a href="%s">here</a> to set up your settings.',
            $this->getManageUrl('payment')
        ) ?>
    </div>
<?php endif;
