<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */
?>
<?php
/**
 * @see Oyst_OneClick_Block_Form_Freepay
 */
?>
<img class="freepay-payment-method-icon v-middle" src="<?php echo $this->getSkinUrl('images/oyst/creditcard.png'); ?>" width="auto" height="auto" alt="<?php echo $this->getPaymentMethodLabel(); ?>" border="0"/>
