<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_OneClick $this
 */
?>

<?php echo $this->addCssStylesBlock(); ?>

<div id="oyst-1click-button-wrapper">
    <!--<?php echo $this->escapeHtml($this->getButtonCustomization('checkout_cart_')); ?> -->
    <div id="oyst-1click-button" <?php echo $this->escapeHtml($this->getButtonCustomization('checkout_cart_')); ?>></div>
</div>

<script>
    (function () {
        if ("function" === typeof oystOneClick) {
            oystOneClick(<?php echo $this->getOneClickUrl(); ?>);
        } else {
            console.error("Missing function oystOneClick");
        }
    })();
</script>
