<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_OneClick $this
 */
?>
<?php
$isWrapper = Mage::getStoreConfigFlag('oyst/oneclick/button_right_position');
$before = Mage::getStoreConfig('oyst/oneclick/button_before_addtocart');
?>
<?php if ($this->isSupportedProduct()) :?>
    <?php if ($isWrapper): ?>
        <div id="oyst-1click-button-wrapper" style="<?php echo $this->getWrapperCustomization(); ?>"></div>
    <?php endif; ?>
    <div id="oyst-1click-button" <?php echo $this->getButtonCustomization(); ?>></div>

    <script>
        getOneclickButton(
            <?php echo $this->getProduct()->getId(); ?>,
            <?php echo $this->getConfigurableProductChildIdIfExist(); ?>,
            <?php echo $this->getOneClickUrl(); ?>,
            <?php echo $this->isProductAddtocartFormValidate(); ?>,
            '<?php echo $before; ?>',
            <?php echo $isWrapper; ?>
        );
    </script>
<?php endif; ?>
