<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_OneClick $this
 */
?>
<?php
if ($this->isSupportedProduct()) :
    ?>
    <div id="oyst-1click-button-wrapper" style="<?php echo $this->getButtonWrapperPosition(); ?>" <?php echo $this->getButtonCustomization(); ?>>
        <div id="oyst-1click-button" <?php echo $this->escapeHtml($this->getButtonCustomization()); ?>></div>
    </div>
    <script>
        <?php echo $this->oneClickButtonPickToFirstAddToCartButtons(); ?>

        (function () {
            if ("function" === typeof oystOneClick) {
                oystOneClick(
                    <?php echo $this->getProductType(); ?>,
                    <?php echo $this->getOneClickUrl(); ?>,
                    <?php echo $this->escapeHtml($this->isProductAddtocartFormValidate()); ?>,
                    <?php echo Zend_Json::encode(
                            Mage::getStoreConfig('oyst/oneclick/product_page_buttons_wrapper_class')
                    ); ?>
                );
            } else {
                console.error("Missing function oystOneClick");
            }
        })();
    </script>
<?php endif;
