<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_OneClick $this
 */
?>
<?php
if ($this->isSupportedProduct()) :
    ?>
    <div id="oyst-1click-button"></div>
    <script>
        (function () {
            if ("function" === typeof oystOneClick) {
                oystOneClick(
                    <?php echo $this->getProduct()->getId(); ?>,
                    <?php echo $this->getConfigurableProductChildIdIfExist(); ?>,
                    <?php echo $this->getOneClickUrl(); ?>,
                    <?php echo $this->isProductAddtocartFormValidate(); ?>
                );
            } else {
                console.warn("Missing function oystOneClick");
            }
        })();
    </script>
<?php endif;
