<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */
?>
<div class='content-header'>
    <table cellspacing='0'>
        <tbody>
            <tr>
                <td><h3 class='head-dashboard'><?php echo Mage::helper('oyst_oneclick')->__('Actions'); ?></h3></td>
            </tr>
        </tbody>
    </table>
</div>

<div id='action-button-container'>
    <p><?php echo Mage::helper('oyst_oneclick')->__("To sync Catalog products with Oyst, click Here : ") ?></p>
    <button onclick="goToThis('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/oyst_catalog/sync') ?>');"
            type='submit' class='scalable task' style=''>
        <span> <span> <span><?php echo Mage::helper('oyst_oneclick')->__('Oyst product sync') ?></span>
        </span>
        </span>
    </button>
    <br/><br/><br/>
</div>

<script type='text/javascript'>
    function goToThis(url) {
        Element.show('loading-mask');
        window.location.href = url;
        //Element.hide('loading-mask');
    };
</script>
