<?php
/**
 * This file is part of Oyst_OneClick for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <plugin@oyst.com> <@oyst>
 * @category Oyst
 * @package Oyst_OneClick
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */

/**
 * @var Oyst_OneClick_Block_OneClick $this
 */
?>
<?php
$product = $this->getProduct();
$oneClickUrl = $this->getOneClickUrl();
?>
<div id="oyst-1click-button"></div>
<script>
    (function() {
        window.__OYST__ = window.__OYST__ || {};
        window.__OYST__.getOneClickURL = function (cb) {
            jQuery(function () {
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                var qty = $("qty").value ? $("qty").value : 1;

                var form = new FormData();
                form.append("productRef", "<?php echo $product->getId(); ?>");
                form.append("quantity", qty);
                var settings = {
                    "async": true,
                    "crossDomain": true,
                    "url": "<?php echo $oneClickUrl ?>",
                    "method": "POST",
                    "headers": {
                        "cache-control": "no-cache"
                    },
                    "processData": false,
                    "contentType": false,
                    "mimeType": "multipart/form-data",
                    "data": form
                };
                jQuery.ajax(settings).done(function (data) {
                    data = JSON.parse(data);
                    cb(true, data.url);
                });
            })
        };
    })();
</script>